
spring.application.name=mindWeave

spring.datasource.url=jdbc:postgresql://ep-polished-star-a149b862.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CHcOo0A7GTth

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:9091}

jwt.secret=mindWeave
jwt.expiration=86400
