
spring.application.name=mindWeave

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:9091}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400}
