
spring.application.name=mindWeave

spring.datasource.url=jdbc:postgresql://ep-abc123.ap-south-1.aws.neon.tech/mindweave?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CHcOo0A7GTth

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=9091

jwt.secret=mindWeave
jwt.expiration=86400
